admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Home:index }

AdminBundle_control:
        resource: "@AdminBundle/Resources/config/routing/control.yml"
        prefix:   /control/