security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\User:
            algorithm:  sha512
            iterations: 1
            encode_as_base64: false
        GN\ConfigBundle\Entity\Usuario: sha512

    role_hierarchy:
        #ROLE_ADMIN:       [ROLE_ENCARGADO, ROLE_SUPERVISOR]
        ROLE_SUPER_ADMIN: [ROLE_ENCARGADO, ROLE_SUPERVISOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: GN\ConfigBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /ingresar
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            remember_me:
                key: dm3600
                lifetime: 3600
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/usuario, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
